### ISSUE TITLE
文字超出屏幕时，无法滚动

### ISSUE THREAD

**Issue by SUWW** [CodeSlaveZhang/ZHSelectableLabel#3]
底部放了一个UIScrollView，在放一个ZHSelectableLabel在UIScrollView的上面，当选择了部分文字后，想滚动到底部看剩余的文字，是无法滚动的，请问这应该如何优化

**Comment by CodeSlaveZhang** [comment]
你说的这种情况的话，可以直接用YYTextView实现的呀- -。我没能复现你说的这个场景。

**Comment by CodeSlaveZhang** [comment]
> 

你说的这种情况的话，可以直接用YYTextView实现的呀- -。我没能复现你说的这个场景。

**Comment by SUWW** [comment]
> > 
> 
> 你说的这种情况的话，可以直接用YYTextView实现的呀- -。我没能复现你说的这个场景。

我在demo复现了哦，代码如下

    UIScrollView *scrollView = [[UIScrollView alloc]initWithFrame:self.view.bounds];
//    scrollView.scrollEnabled =NO;
//    scrollView.showsVerticalScrollIndicator = NO;//隐藏竖滚动条
//    scrollView.showsHorizontalScrollIndicator = NO;
    scrollView.backgroundColor = [UIColor redColor];
    
//    2, 创建bgView
    UIView *bgView = [[UIView alloc]init];
    
    UIView *headView = [[UIView alloc]init];
    headView.backgroundColor = [UIColor greenColor];
    
    
    [self.view addSubview:scrollView];
    [scrollView addSubview:bgView];
    [bgView addSubview:headView];
    
    self.label = [[ZHSelectableLabel alloc]init];
    self.label.numberOfLines = 0;
    self.label.textAlignment = NSTextAlignmentCenter;
    self.label.text = @"Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.";
    [headView addSubview:self.label];
    self.label.userInteractionEnabled = YES;
    [self.label addGestureRecognizer: [[UILongPressGestureRecognizer alloc]initWithTarget:self action:@selector(longPressAction:)]];
    self.label.selectionDeleagte = self;
    
    [scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
//        make.edges.mas_equalTo(self.view);
        make.top.left.right.mas_equalTo(self.view);
        make.bottom.mas_equalTo(self.view).mas_offset(-50);
    }];
    
    [bgView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(scrollView);
        make.width.equalTo(scrollView);
    }];
    
    [headView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.right.equalTo(bgView);
        make.top.equalTo(bgView).offset(0);
        make.height.mas_equalTo(2000);
        make.bottom.mas_equalTo(bgView);
    }];
    
    
    [self.label mas_makeConstraints:^(MASConstraintMaker *make) {
        make.top.bottom.mas_equalTo(headView);
        make.left.mas_equalTo(headView).mas_offset(20);
        make.right.mas_equalTo(headView).mas_offset(-20);

    }];

我之前是用YYTextView的，但是因为加了一些手势进去，YYTextView不太合适了，需要灵活一点的，比如你这种，可以自己添加上去的。

**Comment by CodeSlaveZhang** [comment]
我用你的代码没有复现，可以滑动，并且新的代码添加了选中到底部后自动往下/往上滚动的feature，你可以试试

**Comment by CodeSlaveZhang** [comment]
> > 你说的这种情况的话，可以直接用YYTextView实现的呀- -。我没能复现你说的这个场景。
> 
> 我在demo复现了哦，代码如下
> 
> ```
> UIScrollView *scrollView = [[UIScrollView alloc]initWithFrame:self.view.bounds];
> ```
> 
> // scrollView.scrollEnabled =NO; // scrollView.showsVerticalScrollIndicator = NO;//隐藏竖滚动条 // scrollView.showsHorizontalScrollIndicator = NO; scrollView.backgroundColor = [UIColor redColor];
> 
> // 2, 创建bgView UIView *bgView = [[UIView alloc]init];
> 
> ```
> UIView *headView = [[UIView alloc]init];
> headView.backgroundColor = [UIColor greenColor];
> 
> 
> [self.view addSubview:scrollView];
> [scrollView addSubview:bgView];
> [bgView addSubview:headView];
> 
> self.label = [[ZHSelectableLabel alloc]init];
> self.label.numberOfLines = 0;
> self.label.textAlignment = NSTextAlignmentCenter;
> self.label.text = @"Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.";
> [headView addSubview:self.label];
> self.label.userInteractionEnabled = YES;
> [self.label addGestureRecognizer: [[UILongPressGestureRecognizer alloc]initWithTarget:self action:@selector(longPressAction:)]];
> self.label.selectionDeleagte = self;
> 
> [scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
> ```
> 
> // make.edges.mas_equalTo(self.view); make.top.left.right.mas_equalTo(self.view); make.bottom.mas_equalTo(self.view).mas_offset(-50); }];
> 
> ```
> [bgView mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.edges.equalTo(scrollView);
>     make.width.equalTo(scrollView);
> }];
> 
> [headView mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.left.right.equalTo(bgView);
>     make.top.equalTo(bgView).offset(0);
>     make.height.mas_equalTo(2000);
>     make.bottom.mas_equalTo(bgView);
> }];
> 
> 
> [self.label mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.top.bottom.mas_equalTo(headView);
>     make.left.mas_equalTo(headView).mas_offset(20);
>     make.right.mas_equalTo(headView).mas_offset(-20);
> 
> }];
> ```
> 
> 我之前是用YYTextView的，但是因为加了一些手势进去，YYTextView不太合适了，需要灵活一点的，比如你这种，可以自己添加上去的。

用最新代码试试

**Comment by CodeSlaveZhang** [comment]
> > 你说的这种情况的话，可以直接用YYTextView实现的呀- -。我没能复现你说的这个场景。
> 
> 我在demo复现了哦，代码如下
> 
> ```
> UIScrollView *scrollView = [[UIScrollView alloc]initWithFrame:self.view.bounds];
> ```
> 
> // scrollView.scrollEnabled =NO; // scrollView.showsVerticalScrollIndicator = NO;//隐藏竖滚动条 // scrollView.showsHorizontalScrollIndicator = NO; scrollView.backgroundColor = [UIColor redColor];
> 
> // 2, 创建bgView UIView *bgView = [[UIView alloc]init];
> 
> ```
> UIView *headView = [[UIView alloc]init];
> headView.backgroundColor = [UIColor greenColor];
> 
> 
> [self.view addSubview:scrollView];
> [scrollView addSubview:bgView];
> [bgView addSubview:headView];
> 
> self.label = [[ZHSelectableLabel alloc]init];
> self.label.numberOfLines = 0;
> self.label.textAlignment = NSTextAlignmentCenter;
> self.label.text = @"Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.Objective-C，通常写作ObjC或OC和较少用的Objective C或Obj-C，是扩充C的面向对象编程语言。它主要使用于Mac OS X和GNUstep这两个使用OpenStep标准的系统，而在NeXTSTEP和OpenStep中它更是基本语言。 GCC与Clang含Objective-C的编译器，Objective-C可以在GCC以及Clang运作的系统上编译。 1980年代初布莱德·考克斯(Brad Cox)在其公司Stepstone发明Objective-C。他对软件设计和编程里的真实可用度问题十分关心。Objective-C最主要的描述是他1986年出版的书 Object Oriented Programming: An Evolutionary Approach. Addison Wesley. ISBN 0-201-54834-8.";
> [headView addSubview:self.label];
> self.label.userInteractionEnabled = YES;
> [self.label addGestureRecognizer: [[UILongPressGestureRecognizer alloc]initWithTarget:self action:@selector(longPressAction:)]];
> self.label.selectionDeleagte = self;
> 
> [scrollView mas_makeConstraints:^(MASConstraintMaker *make) {
> ```
> 
> // make.edges.mas_equalTo(self.view); make.top.left.right.mas_equalTo(self.view); make.bottom.mas_equalTo(self.view).mas_offset(-50); }];
> 
> ```
> [bgView mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.edges.equalTo(scrollView);
>     make.width.equalTo(scrollView);
> }];
> 
> [headView mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.left.right.equalTo(bgView);
>     make.top.equalTo(bgView).offset(0);
>     make.height.mas_equalTo(2000);
>     make.bottom.mas_equalTo(bgView);
> }];
> 
> 
> [self.label mas_makeConstraints:^(MASConstraintMaker *make) {
>     make.top.bottom.mas_equalTo(headView);
>     make.left.mas_equalTo(headView).mas_offset(20);
>     make.right.mas_equalTo(headView).mas_offset(-20);
> 
> }];
> ```
> 
> 我之前是用YYTextView的，但是因为加了一些手势进去，YYTextView不太合适了，需要灵活一点的，比如你这种，可以自己添加上去的。

找到你的bug了
你错误的多次调用了startSelection

- (void)longPressAction:(UILongPressGestureRecognizer *)sender{
    **if (sender.state == UIGestureRecognizerStateBegan) {**
        AudioServicesPlaySystemSoundWithCompletion(1519, nil);
        CGPoint positon = [sender locationInView:self.label];
        [self.label startSelectionWithPressPosition:positon];
    }
}

**Comment by SUWW** [comment]
同时还有一个问题，当我加载的是表情包的时候，选择复制，是无法复制到的。比如：我是测试员[emoji_5][emoji_5]。这个是加载了两个表情包，当然这两个表情包是显示表情的。当我全选的时候位置是（0，6）.自由选择后，打印只有：我是测试员，并没有表情包的出现

**Comment by SUWW** [comment]
> startSelection

我下载了最新的代码回来。还是存在问题的。你尝试调用[self.label startSelectionWithRange:NSMakeRange(0, self.label.text.length)];这个方法去显示，因为我是聊天的文本来的，我一开始要全选的。我在demo的操作如下把[self.label startSelectionWithPressPosition:positon];替换成[self.label startSelectionWithRange:NSMakeRange(0, self.label.text.length)];然后长按全选了，之后从上到下滑到到中间，就是相当于截取中间到最后的，然后再长按没截取的部分就又是全选了，之后你就会发现无法滚动了。这个估计是就是你说的多次调用错误？

**Comment by CodeSlaveZhang** [comment]
> > startSelection
> 
> 我下载了最新的代码回来。还是存在问题的。你尝试调用[self.label startSelectionWithRange:NSMakeRange(0, self.label.text.length)];这个方法去显示，因为我是聊天的文本来的，我一开始要全选的。我在demo的操作如下把[self.label startSelectionWithPressPosition:positon];替换成[self.label startSelectionWithRange:NSMakeRange(0, self.label.text.length)];然后长按全选了，之后从上到下滑到到中间，就是相当于截取中间到最后的，然后再长按没截取的部分就又是全选了，之后你就会发现无法滚动了。这个估计是就是你说的多次调用错误？


你打断点看看是否多次调用了startSelected。

**Comment by CodeSlaveZhang** [comment]
> > startSelection
> 
> 我下载了最新的代码回来。还是存在问题的。你尝试调用[self.label startSelectionWithRange:NSMakeRange(0, self.label.text.length)];这个方法去显示，因为我是聊天的文本来的，我一开始要全选的。我在demo的操作如下把[self.label startSelectionWithPressPosition:positon];替换成[self.label startSelectionWithRange:NSMakeRange(0, self.label.text.length)];然后长按全选了，之后从上到下滑到到中间，就是相当于截取中间到最后的，然后再长按没截取的部分就又是全选了，之后你就会发现无法滚动了。这个估计是就是你说的多次调用错误？

出现这种情况的原因是错误的多次调用了startSelect导致label内部多次添加选中手势。
你可以在你长按手势中判断只有longpress.state == begin 才开始选中。或者拉取我最新的代码，最新的代码里面已经防止多次开始选中导致的重复添加手势
