### ISSUE TITLE
富文本加载聊天的表情包时，无法截取到内容

### ISSUE THREAD

**Issue by SUWW** [CodeSlaveZhang/ZHSelectableLabel#4]
当我加载的是表情包的时候，选择复制，是无法复制到的。比如：我是测试员[emoji_5][emoji_5]。这个是加载了两个表情包，当然这两个表情包是显示表情的。当我全选的时候位置是（0，6）.自由选择后，打印只有：我是测试员，并没有表情包的出现

**Comment by CodeSlaveZhang** [comment]
1，确认是使用label.selectedText
2，确认表情的attachment使用的是YYAttachment
3，如果是使用的YYAttachment，确认这段富文本有设置YYTextBackedString

**Comment by SUWW** [comment]
> 1，确认是使用label.selectedText
> 2，确认表情的attachment使用的是YYAttachment
> 3，如果是使用的YYAttachment，确认这段富文本有设置YYTextBackedString

并没有使用label.selectedText的

使用了YYAttachment。代码如下

NSRegularExpression *emojiRegex = [NSRegularExpression regularExpressionWithPattern:@"\\[([^\\[\\]]+)\\]" options:0 error:nil];
    NSArray* emojiMatches = [emojiRegex matchesInString:[text string]
                                                options:NSMatchingWithoutAnchoringBounds
                                                  range:NSMakeRange(0, text.length)];
    NSDictionary *emojiPlistDic = [self readTextToPic];//查找plist文件中表情包的
    for (NSTextCheckingResult* result in [emojiMatches reverseObjectEnumerator]) {
        NSRange matchRange = [result range];
        NSString *placeholder = [text.string substringWithRange:matchRange];
        if ([UIImage imageNamed:emojiPlistDic[placeholder]]) {
            NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包
            [text replaceCharactersInRange:matchRange withAttributedString:attachText];//替换
        }
    }
self.contentLabel.attributedText = text;

**Comment by CodeSlaveZhang** [comment]
> 
解决方案1：
NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包
**这行代码下面新增**
YYTextBackedString *plainstring = [YYTextBackedString stringWithString: placeholder];
[attachText yy_setTextBackedString: plainstring];

解决方案2
项目里面搜索YYTextSimpleEmoticonParser   了解一下

**Comment by CodeSlaveZhang** [comment]
> > 1，确认是使用label.selectedText
> > 2，确认表情的attachment使用的是YYAttachment
> > 3，如果是使用的YYAttachment，确认这段富文本有设置YYTextBackedString
> 
> 并没有使用label.selectedText的
> 
> 使用了YYAttachment。代码如下
> 
> NSRegularExpression _emojiRegex = [NSRegularExpression regularExpressionWithPattern:@"\[([^\\[\\]]+)\]" options:0 error:nil]; NSArray_ emojiMatches = [emojiRegex matchesInString:[text string] options:NSMatchingWithoutAnchoringBounds range:NSMakeRange(0, text.length)]; NSDictionary _emojiPlistDic = [self readTextToPic];//查找plist文件中表情包的 for (NSTextCheckingResult_ result in [emojiMatches reverseObjectEnumerator]) { NSRange matchRange = [result range]; NSString *placeholder = [text.string substringWithRange:matchRange]; if ([UIImage imageNamed:emojiPlistDic[placeholder]]) { NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包 [text replaceCharactersInRange:matchRange withAttributedString:attachText];//替换 } } self.contentLabel.attributedText = text;

**解决方案1：**
NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包
**这行代码下面新增**
YYTextBackedString *plainstring = [YYTextBackedString stringWithString: placeholder];
[attachText yy_setTextBackedString: plainstring];

**解决方案2**
项目里面搜索YYTextSimpleEmoticonParser 了解一下

**Comment by SUWW** [comment]
> > > 1，确认是使用label.selectedText
> > > 2，确认表情的attachment使用的是YYAttachment
> > > 3，如果是使用的YYAttachment，确认这段富文本有设置YYTextBackedString
> > 
> > 
> > 并没有使用label.selectedText的
> > 使用了YYAttachment。代码如下
> > NSRegularExpression _emojiRegex = [NSRegularExpression regularExpressionWithPattern:@"[([^\\[\\]]+)]" options:0 error:nil]; NSArray_ emojiMatches = [emojiRegex matchesInString:[text string] options:NSMatchingWithoutAnchoringBounds range:NSMakeRange(0, text.length)]; NSDictionary _emojiPlistDic = [self readTextToPic];//查找plist文件中表情包的 for (NSTextCheckingResult_ result in [emojiMatches reverseObjectEnumerator]) { NSRange matchRange = [result range]; NSString *placeholder = [text.string substringWithRange:matchRange]; if ([UIImage imageNamed:emojiPlistDic[placeholder]]) { NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包 [text replaceCharactersInRange:matchRange withAttributedString:attachText];//替换 } } self.contentLabel.attributedText = text;
> 
> **解决方案1：** NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包 **这行代码下面新增** YYTextBackedString *plainstring = [YYTextBackedString stringWithString: placeholder]; [attachText yy_setTextBackedString: plainstring];
> 
> **解决方案2** 项目里面搜索YYTextSimpleEmoticonParser 了解一下

我按你建议的方案进行改进：

NSDictionary *emojiPlistDic = [self readTextToPic];//查找plist文件中表情包的
    for (NSTextCheckingResult* result in [emojiMatches reverseObjectEnumerator]) {
        NSRange matchRange = [result range];
        NSString *placeholder = [text.string substringWithRange:matchRange];
        if ([UIImage imageNamed:emojiPlistDic[placeholder]]) {
            NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包
            
            YYTextBackedString *plainstring = [YYTextBackedString stringWithString: placeholder];

            [attachText yy_setTextBackedString:plainstring range:NSMakeRange(0, attachText.length)];
            
            [text replaceCharactersInRange:matchRange withAttributedString:attachText];//替换
            
        }
       
    }

在最后的代理：
- (void)lable:(ZHSelectableLabel *)alable didEndSelectionWithRange:(NSRange)arange
这个的截取范围如何改进？这里截取的是按照转义之后的占位来截取了，因此截取了部分

**Comment by CodeSlaveZhang** [comment]
> > > > 1，确认是使用label.selectedText
> > > > 2，确认表情的attachment使用的是YYAttachment
> > > > 3，如果是使用的YYAttachment，确认这段富文本有设置YYTextBackedString
> > > 
> > > 
> > > 并没有使用label.selectedText的
> > > 使用了YYAttachment。代码如下
> > > NSRegularExpression _emojiRegex = [NSRegularExpression regularExpressionWithPattern:@"[([^\\[\\]]+)]" options:0 error:nil]; NSArray_ emojiMatches = [emojiRegex matchesInString:[text string] options:NSMatchingWithoutAnchoringBounds range:NSMakeRange(0, text.length)]; NSDictionary _emojiPlistDic = [self readTextToPic];//查找plist文件中表情包的 for (NSTextCheckingResult_ result in [emojiMatches reverseObjectEnumerator]) { NSRange matchRange = [result range]; NSString *placeholder = [text.string substringWithRange:matchRange]; if ([UIImage imageNamed:emojiPlistDic[placeholder]]) { NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包 [text replaceCharactersInRange:matchRange withAttributedString:attachText];//替换 } } self.contentLabel.attributedText = text;
> > 
> > 
> > **解决方案1：** NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包 **这行代码下面新增** YYTextBackedString *plainstring = [YYTextBackedString stringWithString: placeholder]; [attachText yy_setTextBackedString: plainstring];
> > **解决方案2** 项目里面搜索YYTextSimpleEmoticonParser 了解一下
> 
> 我按你建议的方案进行改进：
> 
> NSDictionary _emojiPlistDic = [self readTextToPic];//查找plist文件中表情包的 for (NSTextCheckingResult_ result in [emojiMatches reverseObjectEnumerator]) { NSRange matchRange = [result range]; NSString *placeholder = [text.string substringWithRange:matchRange]; if ([UIImage imageNamed:emojiPlistDic[placeholder]]) { NSMutableAttributedString *attachText = [NSMutableAttributedString yy_attachmentStringWithEmojiImage:[UIImage imageNamed:emojiPlistDic[placeholder]] fontSize:15];//加载表情包
> 
> ```
>         YYTextBackedString *plainstring = [YYTextBackedString stringWithString: placeholder];
> 
>         [attachText yy_setTextBackedString:plainstring range:NSMakeRange(0, attachText.length)];
>         
>         [text replaceCharactersInRange:matchRange withAttributedString:attachText];//替换
>         
>     }
>    
> }
> ```
> 
> 在最后的代理：
> 
> * (void)lable:(ZHSelectableLabel *)alable didEndSelectionWithRange:(NSRange)arange
>   这个的截取范围如何改进？这里截取的是按照转义之后的占位来截取了，因此截取了部分

**获取选中的富文本：**
    NSAttributedString *selectedText = [self.attributedText attributedSubstringFromRange:self.selectedRange];
**获取选中的纯文本：**
1，label.selectedText
2,:
    NSAttributedString *selectedText = [self.attributedText attributedSubstringFromRange:self.selectedRange];
    NSString *selectedTextPlain = [selectedText yy_plainTextForRange:selectedText.yy_rangeOfAll];
