### ISSUE TITLE
左右滑动的触发，如何放大点触发范围？

### ISSUE THREAD

**Issue by SUWW** [CodeSlaveZhang/ZHSelectableLabel#5]
如果文字少的时候，很难触发到左右滑动截取。如何放大点左右触发的尼？

**Comment by CodeSlaveZhang** [comment]
修改源码
`- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer`
这个函数里面
`    //左右20像素
    CGFloat xedge = 30;
    CGFloat yedge = 10;
`
这两个值加大，但是不建议加太大

**Comment by CodeSlaveZhang** [comment]
> 如果文字少的时候，很难触发到左右滑动截取。如何放大点左右触发的尼？

针对开始滑动时可触发范围很小的情况，我做了逻辑上的优化。可以尝试一下最新代码。
